### ISSUE TITLE
12.2017 Installer fails to add entry items in mkinittcpio and grub.cfg when using encryptfs

### ISSUE THREAD

**Issue by badmark** [ARCHLabs/Archlabs-Iso#140]
Text based installer provides option for LUKS and LUKS+LVM but fails to add the required entries in mkinitcpio.conf and grub.cfg to load the correct modules in order for the system to boot. 

It also fails to detect Windows partition, despite being found in previous versions and also being founf after install with os-prober and grub-mkconfig.

**Comment by natemaia** [comment]
I've found the issue related to mkinitcpio and LUKS /+ LVM and it should be resolved in the next iso.

Regarding the grub config and finding windows / other distros, I've been having the same issue and working on a fix, for the time being we may have to resort to some post install actions for ease of use, atleast until figuring out what the fix is

Cheers,
Nate

**Comment by badmark** [comment]
That's awesome. If there is anything I can do to help track down the finding other OSes (as it does after booting into the system) Let me know.

(Have you tried running OS prober? I assume you have)

**Comment by badmark** [comment]
Still not working. It's not adding the line into the grub file. I'm attempting to edit it before running but I cannot find the password for liveuser. Could you help?

Error:
grub-install: error attempt to install to encrypted disk without credentials.
GRUB_ENABLE_CRYPTODISK=y is not being added to /etc/default/grub

[Screenshot](https://i.imgur.com/IFhKAqC.jpg)

**Comment by natemaia** [comment]
I've also posted in the relevant thread on the forum as well however 
if you don't catch it there, here is the link [Beta Hotfix 2018.03 ISO Download](https://drive.google.com/open?id=1REjy-wtrLPp68LimpMEuts4CVneAModO)

Still the issue with finding bootloaders, looking around, trying other installers and looking at the filesystem after hasn't gotten me any closer to figuring out why os-prober isnt picking up other bootloaders. So as a temporary fix the post install script (al-hello) will run 
```
grub-mkconfig -o /boot/grub/grub.cfg
```

Much appreciation for the effort on your part

Cheers

**Comment by badmark** [comment]
Awesome, will try in a few. Always glad to help!
